### ISSUE TITLE
Please add support for recent versions of errors

### ISSUE THREAD

**Issue by peti** [chreekat/terminfo-hs#2]
After updating NixOS to errors 2.x, we can no longer built your package: http://packdeps.haskellers.com/feed?needle=terminfo-hs.

**Comment by chreekat** [comment]
Interesting; I have no idea why I had exact bounds on all my deps. Will fix
soon.

**Comment by chreekat** [comment]
Also interesting: In this case the upper bound is correct. errors-2.0 has breaking changes and terminfo-hs doesn't compile against it.

Thanks for bringing this to my attention, but until somebody actually _uses_ this library (which I doubt happens currently :frowning: ) I think I have to deprioritize this issue.

**Comment by peti** [comment]
Well, it's kinda hard for people to use a library that doesn't compile, right?
If this code isn't working with an up-to-date version of its dependencies, then
it's no wonder people hesitate to use it.

**Comment by chreekat** [comment]
Assuming you use stack, terminfo-hs now works for both lts-2.21/ghc-7.8/errors-1.4 or lts-3.1/ghc-7.10/errors-2.0. If you need other environments supported, PRs are welcome.

**Comment by chreekat** [comment]
Eh, boneheaded errors. Reopening. brb.

**Comment by chreekat** [comment]
K, should work now, for Nix as well as most anything else.
